### ISSUE TITLE
Constructing landscape simulations

### ISSUE THREAD

**Issue by jonrhodes** [sLandserve/landscape_simulation#1]
I think it would be good to have the possibility that a cell could be both supply and demand. Maybe that could be dealt with when dealing with interspersion?

**Comment by jonrhodes** [comment]
Can't find the function "scale_fill_viridis_d" to generate the maps.

**Comment by laurajanegraham** [comment]
1. This is how it originally was - we discussed it between the smaller landscape simulation group and many felt it didn't really work, but I can change back and you can see what you think. 

2. This function is in a newer version of ggplot2. I'm not sure if it's in the version on CRAN, so best would be to install the development version (which is what I'm using): 

`install.packages("devtools")`
`devtools::install_github("tidyverse/ggplot2")`

**Comment by jonrhodes** [comment]
1. Yes, I vaguely remember that now. OK, suggest leave it as it is for now.
2. Thanks - that makes sense - will try the development version instead. Can't be in the version on CRAN as that is what I was using.
